apiVersion: v1
data:
  mapRoles: |
    - groups:
      -system:masters
      rolearn: arn:aws:iam::234018720265:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::234018720265:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HLJCDMRB1IBK
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-13T17:41:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1510"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a9478b32-8363-4c67-b141-038ebf1f20de
