apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::000225107645:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FEO7I7E9VVY5
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-05T18:29:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2240"
  uid: e1ad0e9f-4cd6-4d55-bc2b-98df4f5a2ac1
